version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
